- name: Install GPG key for NodeJS LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  become: yes

- name: Install NodeJS LTS repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_8.x xenial main"
    state: present
    update_cache: yes
  become: yes

- name: Install NodeJS
  apt:
    name: nodejs
    state: present
  become: yes
